# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
    - push

jobs:
    build:
        name: "Release: ${{matrix.os}}"
        permissions:
            contents: write

        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore

            - name: zip/compress the build folder
              shell: pwsh
              run: powershell ./zip-build.ps1

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  make_latest: true
                  name: Release ${{ github.ref_name }}
                  tag_name: sha-${{github.sha}}
                  files: |
                      build.zip
